In [12]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([1.2,2.3,3.5])
arr3=np.array([[1,2,3],[4,5,6]])
print(type(arr1),arr1)
print(arr2)
print(arr3)


<class 'numpy.ndarray'> [1 2 3]
[1.2 2.3 3.5]
[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
arr1=np.random.rand(2)
arr2=np.random.randn(2)
arr3=np.random.randint(10,size=(2,2))
arr4=np.random.randint(10,size=(2,2))
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0.47963006 0.5863974 ]
[ 0.26285868 -1.88548093]
[[8 7]
 [2 3]]
[[7 6]
 [2 8]]


In [17]:
import numpy as np
국어=np.array([20,30,60])
영어=np.array([60,40,90])
총점=국어+영어
평균=총점/2
print(총점)
print(평균)
print(np.mean(국어))
print(np.mean(영어))

[ 80  70 150]
[40. 35. 75.]
36.666666666666664
63.333333333333336
