In [11]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
arr2=arr2.flatten()*2
print(arr2)

[ 2  4  6  8 10 12]


In [16]:
import numpy as np
arr=np.arange(5,31,5)
arr

array([ 5, 10, 15, 20, 25, 30])

In [21]:
import numpy as np
arr1=np.zeros([2,3],dtype=int)
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)

[[0 0 0]
 [0 0 0]]
(2, 3)
2
int32
6


In [23]:
import numpy as np
arr1=np.array([[1,2,3,],[4,5,6,],[7,8,9]])
print(arr1)
print(arr1[2,2])
print(arr1[1:3])
print(arr1[arr1<=5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[4 5 6]
 [7 8 9]]
[1 2 3 4 5]
